### ISSUE TITLE
Use Debug Focus + Show Poly Mesh shows strange results

### ISSUE THREAD

**Issue by billowper** [Unity-Technologies/NavMeshComponents#1]
I made a short video to illustrate the behaviour, not sure if intended but the appearance of the navmesh reads like a bug. 

http://files.facepunch.com/billowe/2016/November/02/f359d/2016-11-02_14-47-17.mp4

**Comment by jakobhu** [comment]
The debug vis. was pulled from 5.6 - We're reworking this now.
