### ISSUE TITLE
Error Import NavMeshComponent in Unity 2018.1.3f1

### ISSUE THREAD

**Issue by ftejada17** [Unity-Technologies/NavMeshComponents#111]
Hi all!

I'm trying to import into an empty project the NavMeshComponent that says in the video tutorials esde Gihub. Unity version 2018.1.3f1

When I import the folder Assets-> NavMeshComponents I get the following error by console:
Assets/NavMeshComponents/Scripts/NavMeshSurface.cs(376,52): error CS0117: `UnityEditor.PrefabUtility' does not contain a definition for `GetCorrespondingObjectFromSource'

I have tried with the version of Unity 2018.2.0 and everything works perfect, but with version 2018.1.3f1 it fails.

Does anybody know how I can fix it?

regards

**Comment by ftejada17** [comment]
Ok. I just realized that there are several versions that can be downloaded. I downloaded the Master version and it gave me the error for that.

For the version of Unity that I use 2018.1.3f1 I needed the version of 2018.1

regards

**Comment by turadr** [comment]
I'm glad it worked in the end. Indeed, you need to use the branch that matches the version of your Unity editor.
