### ISSUE TITLE
ETA for full Unity 2018.3 support?

### ISSUE THREAD

**Issue by SharlatanY** [Unity-Technologies/NavMeshComponents#112]
Is there an ETA for fully supporting 2018.3?

Currently, there are e.g some calls to deprecated methods like GetPrefabType(Object).

No biggie since everything seems to work (so far) but just wondering :)

Also, are there any plans to align projects like this, that really are kind of part of Unity a bit better with major releases so they are updated at the same time?

Thanks!

**Comment by turadr** [comment]
Branch `master` is now compatible with Unity 2018.3.
https://github.com/Unity-Technologies/NavMeshComponents/releases/tag/2018.3.0f2

At some time in the future this repo will be published as an Unity package and it will be much easier then to keep it in sync with any changes introduced by other areas of the Unity editor.

**Comment by SharlatanY** [comment]
Thank you very much for the quick fix and the update on the overall status of things; much appreciated! :)
