### ISSUE TITLE
why there are so many bugs when I open it in unity2018.1 such as:

### ISSUE THREAD

**Issue by xueliuxing28** [Unity-Technologies/NavMeshComponents#116]
why there are so many bugs when I open it in unity2018.1 such as:
You are trying to import an asset which contains a global game manager. This is not allowed.
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
Assertion failed: Assertion failed on expression: 'm_AlphaTextures.size() == required'
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
Assets/NavMeshComponents-master/Assets/NavMeshComponents/Scripts/NavMeshSurface.cs(16,6): error CS0246: The type or namespace name `ExecuteAlways' could not be found. Are you missing an assembly reference?

**Comment by turadr** [comment]
Are you using the [2018.1](https://github.com/Unity-Technologies/NavMeshComponents/tree/2018.1)  branch of the repository with Unity 2018.1?
