### ISSUE TITLE
NavmeshSurface bake not working similar to built in bake

### ISSUE THREAD

**Issue by virgilcwylie** [Unity-Technologies/NavMeshComponents#117]
So I tried to apply navmeshsurface to a floating ship. As built in NavMesh baking makes it static, i thought to use this, but then when i baked the ship which had Mesh Collider and not convex, the ship outside walls and sails got baked. :) Which is completely wrong. Can this bake similar to built in NavMesh? I guess that might be simple issue. As the built in baking is already working fine.

**Comment by turadr** [comment]
`NavMeshSurface` does not care about the `static` flag of an object like the built-in baking does. `NavMeshSurface` bakes for the objects represented by its `Collect Objects` selector.
If you need to change how any of those objects affect baking then you can use the [NavMeshModifier](https://docs.unity3d.com/Manual/class-NavMeshModifier.html) component.
