### ISSUE TITLE
5.6.0b4 Not Supported

### ISSUE THREAD

**Issue by xCyborg** [Unity-Technologies/NavMeshComponents#12]
In your readme page here you state that a Unity 5.6.0b2 an up is sufficient to run this project but this is not the case.
I run 5.6.0b4 and got this error. 
`* Assertion at ..\mono\mini\unwind.c:616, condition `cfa_reg != -1' not met`
And nothing new shows up.

**Comment by jakobhu** [comment]
Thx. Fixed - in general the latest master should work with the latest version of Unity.
