### ISSUE TITLE
Loads of errors for unity 2019.1

### ISSUE THREAD

**Issue by PixelSir** [Unity-Technologies/NavMeshComponents#123]
Grabbed the master version for use in unity 2019.1 and i get a ton of errors about namespaces:

![image](https://user-images.githubusercontent.com/33559521/56264906-f2439680-60df-11e9-83ba-94c24f09c11a.png)

How do i fix this? 

And why in the heck is it still not in the package manager so its easier to keep up to date .... its only been like 3 years now.. and far more developed than a lot of preview packages out there.

**Comment by sirchick** [comment]
> Grabbed the master version for use in unity 2019.1 and i get a ton of errors about namespaces:
> 
> ![image](https://user-images.githubusercontent.com/33559521/56264906-f2439680-60df-11e9-83ba-94c24f09c11a.png)
> 
> How do i fix this?
> 
> And why in the heck is it still not in the package manager so its easier to keep up to date .... its only been like 3 years now..and is far more developed than many of the preview packages out there.

**Comment by Red-Cat-Fat** [comment]
First variant. Check your namespace in project. May be VS or your IDE change standart namespace. 
Second variant. What the folder architecture looks like in your project?

**Comment by sirchick** [comment]
There is no conflicting namespaces - the folder architecture has not changed from 2018 and 2019 - not sure why that would change on update.

**Comment by StefDevs** [comment]
I had this issue as well, just ensure you have the "AI" built-in module enabled in the package manager!

**Comment by xCyborg** [comment]
I don't think there is any developer maintaining the repo anymore, it's basically dead since 2 years ago.

**Comment by Claytonious** [comment]
You shouldn't be using the `master` branch with Unity 2019.1, but the `2019.1` branch instead, right?
