### ISSUE TITLE
Warnings in 2019.1

### ISSUE THREAD

**Issue by plasticcow** [Unity-Technologies/NavMeshComponents#124]
There are 3 warning messages in 2019.1 relating to PrefabType

Assets\NavMeshComponents\Editor\NavMeshSurfaceEditor.cs(113,30): warning CS0618: 'PrefabUtility.GetPrefabType(Object)' is obsolete: 'Use GetPrefabAssetType and GetPrefabInstanceStatus to get the full picture about Prefab types.'

Assets\NavMeshComponents\Editor\NavMeshSurfaceEditor.cs(114,31): warning CS0618: 'PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.'

Assets\NavMeshComponents\Editor\NavMeshSurfaceEditor.cs(114,74): warning CS0618: 'PrefabType' is obsolete: 'PrefabType no longer tells everything about Prefab instance.'

**Comment by turadr** [comment]
Have you tried with branches `master` or `2019.1`? I cannot reproduce these warnings.

**Comment by plasticcow** [comment]
Oh wow, sorry.
I was using an old version and upon upgrading my project from 2018 to 2019 encountered the above warnings. Using the latest version on the master removes these warnings.
