### ISSUE TITLE
Physics collision matrix has no effect on nav mesh agents.

### ISSUE THREAD

**Issue by Bunzaga** [Unity-Technologies/NavMeshComponents#13]
I spent a good while trying to figure out why my nav mesh agents continue to collide with each other, even though I set their collision matrix to ignore, and even tried setting Physics.IgnoreLayerCollision.  Nothing worked, then after researching google a bit, it turns out this has been a long standing issue for several years.

Please fix this, or else document it very clearly, that nav mesh agents ignore the collision matrix.

**Comment by jakobhu** [comment]
The navmesh system is completely independent and separate from the physics system. We have plans to add a collision matrix for the navmesh system though.

**Comment by Bunzaga** [comment]
That's great news!  Please be sure to post here when it's being implemented and I'll help test it out.

**Comment by Bunzaga** [comment]
Hey jakobhu.  Is that NavMesh collision matrix going in for this beta/next release, or is it something way down the road?  IE: Should I wait for you to develop it, or come up with a more immediate solution around the current limitations?  I'm working on something with physics similar to a MOBA, where allied players can pass through allied units, but enemy players should not be able to.  However, I don't want them to path around the blocking units, I want them to think they can walk through them, but then bump into them, as though they were physical.

Let me know if you have some advice on how to handle this, and still use the navmesh system.

**Comment by jakobhu** [comment]
Work has not begun yet. The only thing i can say for sure is: 5.6 will _not_ have support for a navmeshagent collision matrix.

**Comment by jakobhu** [comment]
Closing for now - the collision matrix is outside the scope of navmesh building components.

**Comment by CrandellWS** [comment]
Any word on this?

**Comment by Bunzaga** [comment]
Nah, haven't heard anything about this for a while, also haven't had to
deal with nav mesh agents for a bit either...  however I'll be doing some
work on them again soon, so I can let you know if I find anything.
