### ISSUE TITLE
Obstacle carving causes agent warping

### ISSUE THREAD

**Issue by achapin-paladin** [Unity-Technologies/NavMeshComponents#134]
Our team has a scene with a single NavMesh that has multiple floors. If a NavMeshAgent is standing on Floor 2, and a NavMeshObstacle with Carve is pushed next to them, the automatic carving can sometimes carve the spot out under the agent. In this case, they are not on the NavMesh anymore, and therefore re-bind. Rather than rebinding to the closest spot on Floor 2, however, they are warped all the way down to Floor 1 (where there is also a valid NavMesh). This is much further away than F2, and is very unexpected by the player. It seems like the cast is done downwards first instead of looking for the closest valid location. There is no way to intercept this behavior and direct it as we would like.

Unity Version 2018.4.2f1

**Comment by divAxe** [comment]
Hey, I am facing the same issue. Were you able to figure out a solution?

**Comment by turadr** [comment]
This issue has been fixed recently in multiple editor versions.
https://issuetracker.unity3d.com/issues/a-navmeshagent-gameobject-teleports-to-a-near-navmeshsurface-when-collided-with-a-moving-navmeshobstacle
