### ISSUE TITLE
navmesh return error path in 2019.2

### ISSUE THREAD

**Issue by ChangeeZheng** [Unity-Technologies/NavMeshComponents#139]
I found that Navmesh.CalculatePath return an error path in 2019.2,and it worked fine in 2018.3 , you can see the detail in pictures. 

picture_1 : I call the method Navmesh.CalculatePath from point 1 to point 2 , the blue line is the return path but it's error

picture_2: It is navmesh preview.

![QQ图片20190910160629](https://user-images.githubusercontent.com/19769039/64595799-462f7e80-d3e5-11e9-9a30-1f457ff8e268.png)
![QQ图片20190910160714](https://user-images.githubusercontent.com/19769039/64595807-492a6f00-d3e5-11e9-857e-2b516d11756b.png)

**Comment by turadr** [comment]
This issue does not seem related to the NavMeshComponents in this repository. Please use the Unity Bug Reporter to send us a project for reproducing the problem. Thank you.
