### ISSUE TITLE
Make This A Package.

### ISSUE THREAD

**Issue by Filtiarn00** [Unity-Technologies/NavMeshComponents#140]
I think This would make sense to make this A Package in the Package Manager for easy access and smaller project sizes.

**Comment by xCyborg** [comment]
There is no one left here apparently, this has become a ghost repo.

**Comment by dhfjones** [comment]
They're still updating the repo for new releases so there are eyes on it. I also think it would be good for this to be a package, for discoverability if nothing else.

**Comment by turadr** [comment]
Please see this other thread https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-741714518

**Comment by turadr** [comment]
It is now an experimental package for Unity 2019.4 or newer. Please follow this other discussion https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-808105998
