### ISSUE TITLE
Crash - Android Platforms

### ISSUE THREAD

**Issue by ptbarnaby** [Unity-Technologies/NavMeshComponents#144]
Observed throughout 19.3 preview releases, most recently on 2019.3.0b11. Crashes Samsung Galaxy S7 and Oculus Quest (and probably all Android based devices)

**Summary:** A baked NavMeshSurface crashes Android devices on enable when built with IL2CPP

**Detail:** The crash appears to happen within the NavMesh.AddNavMeshData() call from NavMeshSurface.AddData()

**Reproducibility:** 100% (5/5)

**Reproduction steps:**

1. Create a new project on 2019.3
2. Switch platform to Android, enable IL2CPP and .NET 4.x in player settings
3. Import NavMeshComponents
4. Add a NavMeshSurface and bake it (doesn't matter if there are any meshes to bake)
5. Run on an Android device, it should crash as soon as the scene loads

**ADB output:**
[adboutput.txt](https://github.com/Unity-Technologies/NavMeshComponents/files/3863394/adboutput.txt)

**Android Tombstone attached:**
[tombstone_02.txt](https://github.com/Unity-Technologies/NavMeshComponents/files/3863391/tombstone_02.txt)

**Reproduction Project:**
[NavMeshCrash.zip](https://github.com/Unity-Technologies/NavMeshComponents/files/3863505/NavMeshCrash.zip)

**Comment by ptbarnaby** [comment]
On further testing it appears StripEngineCode in Player Settings is the culprit, when turning that off it works correctly.

The underlying bug is tracked at https://issuetracker.unity3d.com/issues/crash-in-navmeshmanager-on-mobile-with-il2cpp and there is further discussion with additional workarounds at https://forum.unity.com/threads/what-is-happen-in-navmeshcomponents-still-alive.761111/

**Comment by tomate-salat** [comment]
> On further testing it appears StripEngineCode in Player Settings is the culprit, when turning that off it works correctly.

Thank you soooo much!!! I had a slightly different problem where the NavMeshManager was causing a NPE. Your hint solved it for me!

**Comment by turadr** [comment]
Thank you for reporting the issue. A fix is on the way, tracked at the link you've posted.

**Comment by turadr** [comment]
Fixed in 2019.3.0f5.
