### ISSUE TITLE
Has unity abandoned this ? 

### ISSUE THREAD

**Issue by PixelSir** [Unity-Technologies/NavMeshComponents#146]
As per the title, seems this feature set has been abandoned - isn't on the package manager...is it still worth using if future support is non existent now?

**Comment by satchell78** [comment]
Was wandering also? Seems legit as a component system, simple to understand. 

-I had a minor issue with the drop plank scene-.

**Comment by ecker00** [comment]
Hope not! Would be great if this was added to the package manager, it works great with latest versions of Unity 2019 and adds those few extra features the NavMesh system seem to be missing at the moment.

**Comment by StewMcc** [comment]
They have updated it for 2019.3, and 2019.3-2D hackweek stuff, but does seem like just absent minded support not active 😞 . Would be nice if updated the package branch though. Currently just added as local package 😕  with some of the PR's / fixes in it.

**Comment by elincoln** [comment]
Good news, it seems: 
https://forum.unity.com/threads/status-and-health-of-navmesh.767696/#post-5119484

> We plan to move NavMesh component to the package manager early next year.
> Support and extensions of NavMesh are currently on hold and will resume in December 2019.
> Expect some news in the beginning of 2020.
> Thank you! 
> NicoFXU, Oct 29, 2019

**Comment by segant08** [comment]
This should be reworked with burst.

**Comment by idbrii** [comment]
More updates. No longer clear timeline for a NavMeshComponents package and their focus is on low-level systems and not NavMeshComponents:

> Hi all, thank you for your patience.
> The Navigation system and the NavMeshComponents repository have mostly been in maintenance mode in the last year or so, with us focusing on solving some of the more pressing issues first.
> This year we plan to make improvements related to the generation of the NavMesh at runtime and to bring the `NavMeshQuery` class to completion and out of the Experimental state. Both goals aim to make the Navigation system more flexible and increase its compatibility with DOTS. Next after that we intend to use the new APIs to transition more and more of Navigation into DOTS systems.
> As you can notice our efforts will focus first on low-level APIs and systems. While we will advance with our plans we might or might not make improvements to the NavMeshComponents code, but at least we will keep it compatible with the latest release of Unity or fix critical bugs. We haven't decided yet when we'll turn that code into a package but we are considering doing that move as soon as we'll evaluate a good progress regarding the main goals that I've mentioned above.
> [adriant, Feb 12, 2020](https://forum.unity.com/threads/status-and-health-of-navmesh.767696/#post-5473656)

and

> In short, is there any reason at all for someone starting a project to use Unity's built-in pathfinding solutions [...]
> We encourage anyone to rely in their projects only on the stable/non-experimental Navigation features, if these cover their needs. As of today, everything that we're working on will take a long time to stabilize.
> [adriant, Jun 10, 2020](https://forum.unity.com/threads/status-and-health-of-navmesh.767696/#post-5960375)

By "experimental" adriant seems to mean how [NavMeshQuery](https://docs.unity3d.com/ScriptReference/Experimental.AI.NavMeshQuery.html) is in the UnityEngine.Experimental.AI namespace. So it seems they still think people should use NavMeshComponents.
