### ISSUE TITLE
Seam created in nav mesh surface that cannot be navigated past by Agents.

### ISSUE THREAD

**Issue by nicbiondi** [Unity-Technologies/NavMeshComponents#154]
This package is really fantastic! However I have found some issues with generating the navmesh that creates seams that cannot be crossed by Agents. I am using quite a few NavMeshObsticals, and by looking through all of them and removing a specific one, it will fix it for that room temporarily. However since the levels are generated dynamically this solution does not work at runtime. I think it has something to do with the logic of the mesh creation thinking something is an edge that is not.

![image](https://user-images.githubusercontent.com/593664/75499504-fe92b400-597e-11ea-95cb-830d72230491.png)

![image](https://user-images.githubusercontent.com/593664/75499443-d60aba00-597e-11ea-84e0-62b188f34bb3.png)

**Comment by turadr** [comment]
I believe you describe the same issue reported here https://issuetracker.unity3d.com/issues/navmesh-navmesh-fails-to-create-all-portals-connecting-two-tiles-when-having-obstacles-aligned-on-the-tile-borders , which has been fixed. Let us know please if the problem persists after you update the editor to a newer patch version.

**Comment by turadr** [comment]
If anyone encounters this issue again please let us know through the [Bug Reporter](https://unity3d.com/unity/qa/bug-reporting).
