### ISSUE TITLE
How to send a signal when a runtime navmesh is created?

### ISSUE THREAD

**Issue by rampagedog12** [Unity-Technologies/NavMeshComponents#155]
I create a navmesh on a terrain runtime, but the creation spends a long time. Thus, I will get an error if I let the AI appear on the terrain... I want to make a loading scene and it will show everything when the creation of a runtime navmesh is finished. I am using LocalNavMeshBuilder. It seems that the navmesh is created via UpdateNavMesh...

**Comment by turadr** [comment]
You can modify the code to call `NavMeshBuilder.UpdateNavMeshDataAsync()`. This method returns an `AsyncOperation` object that has a `completed` property to which you can register the event you wanted. An alternative would be to check if this operation `isDone` every frame.

https://docs.unity3d.com/ScriptReference/AI.NavMeshBuilder.UpdateNavMeshDataAsync.html
https://docs.unity3d.com/ScriptReference/AsyncOperation.html

**Comment by rampagedog12** [comment]
@turadr I check LocalNavMeshBuilder.cs. It seems to use UpdateNavMeshData() to generate NavMesh, which only returns boolean, while it update NavMesh in runtime using UpdateNavMeshDataAsync().....

**Comment by turadr** [comment]
`LocalNavMeshBuilder` has a private member `AsyncOperation m_Operation;` . You need to modify the code to make it public or write a `get` accessor for it. Then you can access it in your code to check if the operation is done or to register the event for when it will be completed.

**Comment by rampagedog12** [comment]
@turadr I mean... It loops UpdateNavMesh(true) in IEnumerator, This is only for updates on NavMesh, so there will be many m_Operation.isDone? However, I only want the signal when the creation of NavMesh is finished... Do I misunderstand IEnumerator? I am new to Unity...... Dose LocalNavMeshBuilder use UpdateNavMesh(false) to create NavMesh and then use UpdateNavMesh(true) to update NavMesh?

**Comment by turadr** [comment]
The NavMesh is created and instantiated in `OnEnable()`. It is first updated in that same method when `UpdateNavMesh(false)` is called. This is a synchronous call, so right after that the NavMesh has been created in its first form. You can write your own mechanism for notifying other systems and call it right there. 
After that the NavMesh is continuously updated in case changes occur in the sources. Yes, you'll get m_Operation.isDone equal to true very often, probably every frame if nothing changes in the scene. If you need to know that the NavMeshData has actually changed after a `UpdateNavMeshData()` or `UpdateNavMeshDataAsync()` operation is completed then there is no way currently to do that.

I think you can change `UpdateNavMesh(false)` to `UpdateNavMesh(true)` and this way `m_Operation` will allow you to follow the progress of when the NavMesh is updated for the first time (same as saying "it has been created").
