### ISSUE TITLE
Package Manager

### ISSUE THREAD

**Issue by praleks** [Unity-Technologies/NavMeshComponents#156]
You should definitely add this package to PM

**Comment by turadr** [comment]
We know having this code in a package would be useful to you and other users. We are still evaluating the possibility of doing this transition soon. We'll let everyone know when that will happen. Thank you for your feedback and your patience.

**Comment by turadr** [comment]
Please see this other thread https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-741714518

**Comment by turadr** [comment]
It is now an experimental package for Unity 2019.4 or newer. Please follow this other discussion https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-808105998
