### ISSUE TITLE
Unity 2020.1 Beta Warns: PrefabStage.prefabAssetPath is obsolete.

### ISSUE THREAD

**Issue by Ziflin** [Unity-Technologies/NavMeshComponents#163]
After installing Unity 2020.1 beta,  `NavMeshAssetManager.cs` issues two warnings for:

> Assets\Packages\Unity\NavMeshComponents\Editor\NavMeshAssetManager.cs(44,61): warning CS0618: 'PrefabStage.prefabAssetPath' is obsolete: 'prefabAssetPath has been deprecated. Use assetPath instead.'

**Comment by turadr** [comment]
The warning have now been solved in the `2020.1` branch.
