### ISSUE TITLE
There is no way how to access / get to know anything about NavmeshLink from agent when traversing offmeshlink

### ISSUE THREAD

**Issue by PetrSovis** [Unity-Technologies/NavMeshComponents#17]
When an agent is traversing offmeshlink (agent.isOnOffMeshLink == true), there's a possibility to obtain runtime OffMeshLinkData structure by accessing agent.currentOffMeshLinkData.
There's a member OffMeshLinkData.OffMeshLink which points to a user supplied off-mesh link. Then you can access gameObject and access additional components to read information about the move it's supposed to be done.
However, there's no such option for NavMeshLink although there's a owner member in link instance. 
This disables implementing different moves (with additional data stored in similar classes like NavMeshLink). 
Or am I missing something ?
Best regards
Petr
P.S. by the way, subclassing / inheritance enabled on OffMeshLink would be more then welcome

**Comment by jakobhu** [comment]
Yes - we should probably deprecate that functionality. Use instead https://docs.unity3d.com/560/Documentation/ScriptReference/AI.NavMeshAgent-navMeshOwner.html to obtain the owner of the current location (navmesh or link instance) - the return type is Object.

**Comment by PetrSovis** [comment]
Thanks! This should fix my problems. 
I overlooked this (not very obvious)
P.
