### ISSUE TITLE
How to Set sourceObject value?

### ISSUE THREAD

**Issue by BUGyyc** [Unity-Technologies/NavMeshComponents#177]
just like:

NavMeshBuildSourceShape.Box

the code:

`            var mf = m_boxColliders[i];
            if (mf == null) continue;
            // var m = mf.sharedMesh;
            // if (m == null) continue;
            var s = new NavMeshBuildSource();
            s.shape = NavMeshBuildSourceShape.Box;
            // is error
            // s.sourceObject = m;
            s.transform = mf.transform.localToWorldMatrix;
            s.area = 0;
            sources.Add(s);
`

how to set value?

**Comment by turadr** [comment]
`sourceObject` is only used when you set `s.shape` to `NavMeshBuildSourceShape.Mesh` or `NavMeshBuildSourceShape.Terrain`. 
Example:
```var gameObject = GameObject.CreatePrimitive(PrimitiveType.Cube);
var source = new NavMeshBuildSource
{
    area = 0,
    shape = NavMeshBuildSourceShape.Mesh,
    component = gameObject.GetComponent<MeshRenderer>(),
    sourceObject = gameObject.GetComponent<MeshFilter>().sharedMesh,
    transform = box.transform.localToWorldMatrix,
    size = Vector3.zero
};
```

https://docs.unity3d.com/ScriptReference/AI.NavMeshBuildSource-sourceObject.html
