### ISSUE TITLE
NavMeshAgents aligning to NavMeshSurface even with updateRotation set to false

### ISSUE THREAD

**Issue by jamesShasha** [Unity-Technologies/NavMeshComponents#18]
NavMeshAgent rotates the transform to align with the nav mesh normal even if updateRotation is set to false. Maybe I'm missing something? This behavior is new as far as I can tell.

**Comment by jakobhu** [comment]
`updateUpAxis` should be set to `false` if you don't want the NavMeshAgent to align to the up axis of the NavMesh it's placed on. updateRotation controls whether the heading of agent should be updated.

**Comment by jamesShasha** [comment]
perfect! thanks so much
