### ISSUE TITLE
Package branch: Author is missing

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/NavMeshComponents#192]
The package.json is missing author information. This should not pass package validation CI, and will show up incorrectly inside Unity (author is "Other", not "Unity Technologies"). Please add proper author information :)

https://github.com/Unity-Technologies/NavMeshComponents/blob/af533d13ea89b550ba4597a1c0cccebfcf1c9118/package.json#L10

**Comment by turadr** [comment]
We can't add the author field. 
"A Unity package must not have an author field."
Source: https://docs.unity3d.com/Packages/com.unity.package-validation-suite@latest/index.html?preview=1&subfolder=/manual/manifest_validation_error.html%23a_unity_package_must_not_have_an_author_field

**Comment by hybridherbst** [comment]
This package isn't released via Unity PackageManager on the Unity registry, or is it? As long as it's not, the author information should be present in the package.json so people using it via git or OpenUPM get proper info.
I suggest you talk to the package validation people on allowing Unity author to be present.

**Comment by turadr** [comment]
If the `author` field is missing the Unity editor deduces the author to be Unity Technologies.
I'm not familiar with the other registries. Could you give me a quick example of where this author name will show up in other systems?

**Comment by turadr** [comment]
Until the package will be release on the Unity Registry I've added the author name in the .json file with 048a238c56ce33f78a1486cc20ec6c8661d47199 .

**Comment by hybridherbst** [comment]
Feel free to try it out:

If you go to Package Manager, click "+", select "git package", and enter
https://github.com/Unity-Technologies/NavMeshComponents.git#7f8fda26fdc582e81c892c64dfec70e8dfda0aba (the commit before you added the author information), you get:
![image](https://user-images.githubusercontent.com/2693840/101906842-eb716d80-3bb9-11eb-813f-83adf2c676f7.png)

If you change it to
https://github.com/Unity-Technologies/NavMeshComponents.git#package you'll get the latest package commit where Author information is correct.

This seems to be hardcoded to show "Unity Technologies" if a package is from the Unity Registry, unless packages override it (e.g. FBX SDK, Havok physics and Vuforia explicitly set the author).

**Comment by turadr** [comment]
Alright, thanks! I've missed that detail.
