### ISSUE TITLE
Package branch: package.json does not contain samples but Samples~ folder exists

### ISSUE THREAD

**Issue by hybridherbst** [Unity-Technologies/NavMeshComponents#194]
Samples should be specified in the package.json so that users can import them via Package Manager.
I looked at the Samples~ folder and it seems currently everything is one big sample, which is fine, but would be better to have smaller, separate ones as that makes it clear from PackMan what is imported when using a sample.

**Comment by turadr** [comment]
Thanks for reporting this issue. I've fixed it in 7f8fda26fdc582e81c892c64dfec70e8dfda0aba .
