### ISSUE TITLE
Crash in large scene with lots of staticly carving NavMeshObstacles instantiated at runtime

### ISSUE THREAD

**Issue by billowper** [Unity-Technologies/NavMeshComponents#2]
[crash_aec8d41fb8260c41baa5d2b60a9f0577.zip](https://github.com/Unity-Technologies/NavMeshComponents/files/567082/crash_aec8d41fb8260c41baa5d2b60a9f0577.zip)

**Comment by jakobhu** [comment]
fixed since 5.5exp/5.6+
