### ISSUE TITLE
NavMeshAgent isnt exposing agentTypeID

### ISSUE THREAD

**Issue by sniffle6** [Unity-Technologies/NavMeshComponents#20]
Unity is giving this error on clone

Assets/Plugins/Navigation/Tests/NavMeshSurfaceAgentTests.cs(55,15): error CS1061: Type `UnityEngine.AI.NavMeshAgent' does not contain a definition for `agentTypeID' and no extension method `agentTypeID' of type `UnityEngine.AI.NavMeshAgent' could be found. Are you missing an assembly reference?

**Comment by jakobhu** [comment]
yup - sry. I pushed these tests a bit too early ("GitHub desktop" seemingly doesn't push the selected rev. but everything) - a fix is expected for 5.6.0p1.

For now you can update to the 5.6 branch: https://github.com/Unity-Technologies/NavMeshComponents/tree/5.6

**Comment by jakobhu** [comment]
To avoid further confusion I've commented out the test code for now.
