### ISSUE TITLE
2019.4.17f1 - NavMeshComponent's navemesh does not show the blue navmesh in editor viewport

### ISSUE THREAD

**Issue by fkkcloud** [Unity-Technologies/NavMeshComponents#205]
Hello,

In 2019.4.17f1, NavMeshComponent's baked navmesh does not show the blue navmesh in editor view.
The Navmesh data is there but it only shows the white boundbox but not the usual blue navmesh.
![feaewfa](https://user-images.githubusercontent.com/3806802/109922214-dca6ce00-7c71-11eb-96ac-afc2c43e4545.png)

**Comment by turadr** [comment]
Hi, 
Is a NavMeshAgent able to find and move on that NavMesh?
Also, do you have the "Gizmos" button enabled?
![image](https://user-images.githubusercontent.com/9038468/109963896-3b5d5d80-7ced-11eb-9f00-49174aca087c.png)

**Comment by fkkcloud** [comment]
I have turned it on. It works with regular generic unity plane btw. I can see the blue navmesh but not with this mesh.
[city_ground_d.zip](https://github.com/Unity-Technologies/NavMeshComponents/files/6083694/city_ground_d.zip)

**Comment by turadr** [comment]
The NavMesh is not displayed because it is probably not generated, as reported in issue #206 .
