### ISSUE TITLE
Bake-function documented, not implemented

### ISSUE THREAD

**Issue by jaakaappi** [Unity-Technologies/NavMeshComponents#22]
The documentation mentions a Bake-function for the NavMeshSurface compoment but it seems to not have been implemented yet. Is this the case?

https://docs.google.com/document/d/1usMrwMHTPNBFyT1hZRt-nQZzRDTciIQRVzmA7MQsFNw/edit#

**Comment by diondokter** [comment]
That's just a draft, but it'd be nice if there'd be an updated version.

**Comment by jaakaappi** [comment]
Yeah.. because that functionality is pretty much the sole reason for me to move to the new system. I understand that it's a draft and under active development, but indication of stuff that has not yet been done should be added. It's a matter of adding or removing an asterisk after a days work.

**Comment by jakobhu** [comment]
was 'Bake' - now 'BuildNavMesh', docs now fixed

**Comment by jaakaappi** [comment]
Ahh, okay. Thanks :)
