### ISSUE TITLE
FAQ - Bake and efficiently Update navmesh surfaces at runtime?

### ISSUE THREAD

**Issue by nicobella** [Unity-Technologies/NavMeshComponents#23]
Hi, I have a question that's probably on many users head, do you have an already tutorial or docs showing how to programatically bake a navmesh surface on runtime? and more specifically, how to update a navmesh surface on runtime after some modification like a **NavMesh Modifier Volume** has been created? in my case for example I create a modifier volume to alter the cost of the navmesh surrounding a newly placed tower in a TD style game, then units will avoid that area which is a higher cost area, I want to do this at runtime every time I place a new tower, but also I don't want to re-bake the entire navmesh, the draft documentation says that things like carving the mesh can take advantage of the tiling so for example only the tiles affected will be updated. thanks!

**Comment by diondokter** [comment]
I've been stuck with that problem as well. And also just updating the addition and removal of the mesh in a small area (tile game). It's not clear how one should update/bake an area/portion of the mesh.

**Comment by Leopotam** [comment]
You should update whole bounds - looks like unity check navmesh sources list for changes and rebake it. For performance optimization you can tweak tile-size / voxel-size parameters - for decrease size of each navmesh grid cell (only changed cells will be updated).

**Comment by PolygonSoup** [comment]
I've been trying to look for a solution as well. I even opened up a thread here:
https://forum.unity.com/threads/how-to-procedurally-build-the-area-cost-of-a-mesh-into-the-navmesh-during-runtime.503172/
I **think** you can update it using [NavMeshBuilder.UpdateNavMeshData](https://docs.unity3d.com/ScriptReference/AI.NavMeshBuilder.html)
Unfortunately, I haven't yet got the desired result. I am still experimenting further with that function. Hopefully, Unity will release a feature soon.

**Comment by PolygonSoup** [comment]
I was able to find a solution thanks to DwinTeimlon: 
https://forum.unity.com/threads/navmesh-modifier-or-navmesh-modifier-volume-at-run-time.487632/

**Comment by turadr** [comment]
General beginner-level tutorials about **Runtime NavMesh Generation** can be found in the [Navigation](https://unity3d.com/learn/tutorials/s/navigation) section of the [Unity Tutorials](https://unity3d.com/learn/tutorials/s/navigation) page.

Also this video from Unite 2017 can prove helpful: [Finding the path: New navigation features](https://www.youtube.com/watch?v=n-RXnDGE72M) .
