### ISSUE TITLE
Default Area "Non-walkable", with modifier volumes walkable?

### ISSUE THREAD

**Issue by joethephish** [Unity-Technologies/NavMeshComponents#26]
Hey, great work on the new NavMesh features, they're really exciting to see!

I couldn't get the following to work, not sure whether it's a bug or intended behaviour:

I'm attempting to set up a NavMesh where I have full control over which areas are walkable using a set of volumes. I was hoping to be able to set the default area to "non-walkable", so that by default, nothing gets added to the NavMesh, but then add multiple NavMeshModifierVolume objects so that I could "cut into" the empty space, and create walkable areas.

The use case is that I have quite a large map with a small set of paths that I want to be traversable.

Is there a way to do that? Or perhaps I'm going about this the wrong way?

Many thanks!

**Comment by jakobhu** [comment]
Currently that's not possible unfortunately. From: https://docs.unity3d.com/Manual/nav-AreasAndCosts.html

"_If several objects of different area types are overlapping, the resulting navmesh area type will generally be the one with the highest index. There is one exception however: Not Walkable always takes precedence. Which can be helpful if you need to block out an area._"

Catering for the opposite of your use case ..

**Comment by joethephish** [comment]
Okay, thanks anyway :-(
