### ISSUE TITLE
LocalNavMeshBuilder only working for the Humanoid agent.

### ISSUE THREAD

**Issue by r3eckon** [Unity-Technologies/NavMeshComponents#27]
The LocalNavMeshBuilder script only seems to work with a single agent type. By looking at the script I found out that the NavmeshAgent ID is hardcoded to 0 ( Humanoid ). A simple fix could be to allow users to enter which agent ID should be used by this particular NavmeshBuilder.

`public int agentID = 0;`

```
void UpdateNavMesh(bool asyncUpdate = false)
    {
        NavMeshSourceTag.Collect(ref m_Sources);
        var defaultBuildSettings = NavMesh.GetSettingsByID(agentID);
        var bounds = QuantizedBounds();

        if (asyncUpdate)
            m_Operation = NavMeshBuilder.UpdateNavMeshDataAsync(m_NavMesh, defaultBuildSettings, m_Sources, bounds);
        else
            NavMeshBuilder.UpdateNavMeshData(m_NavMesh, defaultBuildSettings, m_Sources, bounds);
    }
```

**Comment by jakobhu** [comment]
yeah - the examples are not meant to be generic.

**Comment by pedro15** [comment]
if don't know if there is a way to get the list of the agent types .. if there is a way to do that , an custom Inpector can be written to simply select the agentType by a dropdown list :)

**Comment by r3eckon** [comment]
Thanks for clearing that up, I thought getting the other agent IDs happened somewhere else along the navmesh building pipeline. I'll just use this solution as it seems to be working for me.

**Comment by jakobhu** [comment]
there's a utility function for the editor side - see link editor for ex.:

https://github.com/Unity-Technologies/NavMeshComponents/blob/master/Assets/NavMeshComponents/Editor/NavMeshLinkEditor.cs#L78

**Comment by r3eckon** [comment]
Very nice, thanks for memntioning this.
