### ISSUE TITLE
NavMesh Source Tag only working on axis lines

### ISSUE THREAD

**Issue by radman5** [Unity-Technologies/NavMeshComponents#35]
Hi :)

I am trying use the LocalNavMeshBuilder and SourceTag scripts from the examples for my modularly built levels. I have weird behaviour that the surfaces are only being generated when the are intersected by the X and Z axis 0 lines.

Super weird right??

![dynamic navmesh not working](https://cloud.githubusercontent.com/assets/5211042/26510201/56d6b5fa-42b0-11e7-89be-55a18c9d3d68.PNG)

**Comment by jakobhu** [comment]
For an explanation see https://docs.unity3d.com/Manual/nav-AdvancedSettings.html (min region area) . The support for `minRegionArea` for runtime building navmesh will be available soon in 5.6 (is currently available in 2017 beta).

**Comment by radman5** [comment]
Thanks @jakobhu :) I understand now
