### ISSUE TITLE
Request: Expose NavMesh "Agent" data

### ISSUE THREAD

**Issue by NikiWalkerDeveloper** [Unity-Technologies/NavMeshComponents#37]
Hey,

Overall, fantastic API, thanks for building it. We just stumbled upon some missing functionality. 

The API has a concept of "Areas" ("Walkable", "Not Walkable" etc.), and a concept of "Agents" ("Humanoid", "Vehicle" etc.).

Currently, SamplePosition, Raycast and FindClosestEdge can specify which areas to query, but not which "Agents" NavMesh to query. As we build one NavMesh per "Agent" type (otherwise referred to as "Settings"), the results of SamplePosition are vastly different for different Agents. 

The NavMeshHit struct similarly only exposes "Area". 

Proposed solution: Expose an int mask for "Agent" in the queries, and add an int "Agent" mask to the NavMeshHit struct.

Example use case of improved system:

    if(NavMesh.SamplePosition(queryPos, radius, out navMeshHit, NavMesh.AllAreas, humanoidAgentMask | vehicleAgentMask))
    {
        if(hit.agentId == humanoidAgentId)
        {
            // We hit the "Humanoid" area NavMesh.
        }
        // Else we hit the "Vehicle" area NavMesh.
    }

NavMeshAgents must be querying for their own NavMesh to function correctly anyway, so my assumption is that this should be fairly simple?

The current hacky solution is to make an "Area" per "Agent". 

Thanks!

**Comment by jakobhu** [comment]
These functions are already overloaded to support what you suggest - albeit in a slightly different way - using the 'NavMeshQueryFilter' - which contains the agent type id - see also : https://docs.unity3d.com/ScriptReference/AI.NavMeshQueryFilter.html

**Comment by NikiWalkerDeveloper** [comment]
Whoops, completely missed that. Thanks! Might be worth adding the overloads to the docs for the above functions.

**Comment by jakobhu** [comment]
hmm it should be in the docs also : e.g. https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html
