### ISSUE TITLE
NavMeshSurface Includes Trigger Colliders

### ISSUE THREAD

**Issue by andrewgotow** [Unity-Technologies/NavMeshComponents#38]
The `NavMeshSurface` Component's `UseGeometry` parameter includes trigger volumes when set to `PhysicsColliders` This can cause unexpected behavior, especially in scenes with many overlapping triggers.

**Comment by jakobhu** [comment]
I suggest using the layer mask for filtering triggers. Most projects i guess have a separate layer for triggers already.

**Comment by hadesfury** [comment]
It is a good workaround but shouldn’t it be fixed ?
