### ISSUE TITLE
NavMesh on small plane

### ISSUE THREAD

**Issue by SquareLi** [Unity-Technologies/NavMeshComponents#39]
I'm not able to generate navmesh on a object that is smaller than 1,1,1. Is it a known limitation? In order to have the navmesh working properly, the platform has to be larger than 2.

**Comment by Arugin** [comment]
It heavily depends on Navmesh agent radius. If it's radius is large, there will be no space on the small plane for it.

**Comment by turadr** [comment]
That is correct, if the agent radius is 0.5 (as it is by default) the object is smaller than 1,1,1 there isn't enough room on all sides for the agent to fit.
