### ISSUE TITLE
Any plans for a Good Local Avoidance ?

### ISSUE THREAD

**Issue by pedro15** [Unity-Technologies/NavMeshComponents#4]
I am very happy that you guys are improving the navigation system. But i don't see in the 'experimental' features some Improvements with the avoidance. actually the "local avoidance" of the navmesh agent it simply does not work. it gets confused / pushing other agents. so i really HOPE that you add a real local avoidance. that the agents can prevent collision with others.

**Comment by DamienDoury** [comment]
+1

**Comment by sakirma** [comment]
+1

**Comment by jakobhu** [comment]
It's noted, we want to make this more flexible. However the local avoidance behaviour is not part of the components for navmesh building - so closing this one.
