### ISSUE TITLE
[2017.2] script compilation error

### ISSUE THREAD

**Issue by MightyCreak** [Unity-Technologies/NavMeshComponents#40]
Hi!

Just copied the project assets directory in my 2017.2 project and there is a compilation error in `NavMeshSurface.DrawGizmo()`:
```Assets/NavMeshComponents/Scripts/NavMeshSurface.cs(430,38): error CS0117: `UnityEditor.AI.NavMeshEditorHelpers' does not contain a definition for `DrawSurface'```

**Comment by Claytonious** [comment]
Can confirm - same here so it's nothing specific to your project.

**Comment by turadr** [comment]
It has been fixed.
