### ISSUE TITLE
Warning with 2017.1.1p1

### ISSUE THREAD

**Issue by jramstedt** [Unity-Technologies/NavMeshComponents#42]
Assets/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(21,42): warning CS0618: `UnityEditor.IMGUI.Controls.BoxBoundsHandle.BoxBoundsHandle(int)' is obsolete: `Use parameterless constructor instead.'

**Comment by TMaloteaux** [comment]
This is fixed in the 2017.1 branch.
