### ISSUE TITLE
NavMeshSurface.SamplePositon ?

### ISSUE THREAD

**Issue by Petethegoat** [Unity-Technologies/NavMeshComponents#44]
Will this function be added, or is there a different way to do the same thing?
https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html

**Comment by HilariousCow** [comment]
Hey!
It's my understanding that there is a work around if you want to sample just one NavMeshSurface. But you're not going to like it.

So, basically, the NavMesh class has a list of loaded NavMeshSurfaces. Whatever's loaded on there is what it uses to calculate paths, or sample points, or do RayCasts.

So if you want to sample from just one NavMeshSurface, you need to 
1. Unload all data from the NavMesh singleton ( https://docs.unity3d.com/ScriptReference/AI.NavMesh.RemoveNavMeshData.html )
2. Load the desired NavMesh 
3. Sample

4. Load the previously loaded NavMeshes (for each active scene, get each NavMeshSurface in the scene,
 and reload it using: https://docs.unity3d.com/ScriptReference/AI.NavMesh.AddNavMeshData.html)

It's a bit of a work around, but it's possible, and +1 desire for it to be added.

**Comment by Petethegoat** [comment]
Thanks for the workaround!
At the moment I only have a single surface so that's not too bad for me.

**Comment by turadr** [comment]
Hi,
To sample just one surface you can use the following function overload to provide the `navMeshSurface.agentTypeID` of the surface you target, through the QueryFilter parameter:
`public static bool SamplePosition(Vector3 sourcePosition, out AI.NavMeshHit hit, float maxDistance, AI.NavMeshQueryFilter filter); `

Docs: https://docs.unity3d.com/ScriptReference/AI.NavMesh.SamplePosition.html 

No need to remove the other surfaces and add them back.
