### ISSUE TITLE
Deprecated methods in 2017.2.0.f3

### ISSUE THREAD

**Issue by cfoulston** [Unity-Technologies/NavMeshComponents#45]
I'm sure you guys are aware, but getting these warnings after importing the 2017.2 branch:

Assets/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(108,22): warning CS0618: `UnityEditorInternal.EditMode.DoEditModeInspectorModeButton(UnityEditorInternal.EditMode.SceneViewEditMode, string, UnityEngine.GUIContent, UnityEngine.Bounds, UnityEditor.Editor)' is obsolete: `Use signature passing Func<Bounds> rather than Bounds.'

Assets/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(21,42): warning CS0618: `UnityEditor.IMGUI.Controls.BoxBoundsHandle.BoxBoundsHandle(int)' is obsolete: `Use parameterless constructor instead.'

Assets/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs(443,22): warning CS0618: `UnityEditorInternal.EditMode.DoEditModeInspectorModeButton(UnityEditorInternal.EditMode.SceneViewEditMode, string, UnityEngine.GUIContent, UnityEngine.Bounds, UnityEditor.Editor)' is obsolete: `Use signature passing Func<Bounds> rather than Bounds.'

Assets/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs(60,42): warning CS0618: `UnityEditor.IMGUI.Controls.BoxBoundsHandle.BoxBoundsHandle(int)' is obsolete: `Use parameterless constructor instead.'

**Comment by federicorosso1993** [comment]
same here.

**Comment by RenegadePawn** [comment]
Same problem here. The code hasn't been updated in like 6+ months.

**Comment by turadr** [comment]
It works now.

**Comment by paulpach** [comment]
I just checked out master and I am seeing this warning.   Where did you fix the problem?

**Comment by turadr** [comment]
@paulpach You were right, only a part of those warnings had been fixed previously. I've now solved the remaining ones. Sorry for the inconvenience.
