### ISSUE TITLE
Height Mesh support

### ISSUE THREAD

**Issue by ftsf** [Unity-Technologies/NavMeshComponents#46]
I noticed there's no issue for adding height mesh support yet.

Is this planned, if not is there a way to use a custom height mesh or similar workaround?

**Comment by turadr** [comment]
Adding height mesh support is in our plans, but not for the near future. It is not currently possible to use a custom height mesh, unfortunately.

**Comment by marcospgp** [comment]
It's been a few years, do you guys have any specific plans for height mesh building now?
