### ISSUE TITLE
NavMesh empty

### ISSUE THREAD

**Issue by dav101** [Unity-Technologies/NavMeshComponents#47]
Hi there,
I am trying to dynamically create a navmesh by a script, I have a plane which is created dynamically and it's position is constantly updated. I add the navMeshSurface component and build the navMesh, however it's empty. Looking through it using the NavMeshTriangulations I see the vertices and triangles are 0.  The dynamically created object has a plane mesh (mesh filter) and that mesh has real values for vertices and triangles, when this plane mesh is used to generate a navmesh it doesn't work as I get 0 triangles and vertices. Note the dynamically created object has a scale of less than 0, Does this affect it?

**Comment by turadr** [comment]
Hi,
Yes, negative scale affects it. A plane with negative Y scale is considered flipped and thus will not pass the "Max Slope" condition described by the agent type. As an example, consider a positive-scale plane, like the floor of a room. Once we change the Y-scale to be negative, the plane normal flips and it becomes similar to the ceiling. It is not allowed to bake for both floor and ceiling orientations at the same time. 
I tried with a plane to set Y scale -1 and rotation on the X axis to 180 degrees and the plane baked just fine.
Why do you need it to have negative scale?
