### ISSUE TITLE
Feedback.

### ISSUE THREAD

**Issue by t9s1n2** [Unity-Technologies/NavMeshComponents#5]
I'm hoping one day i'll be able to use this system for randomly generated dungeons. For that i'll basically need the baking system you can use in edit mode with NavMeshSurfaces. Why can't that system simply be possible to be called somehow from play mode for now? If it's a speed issue then it would still be really handy for some games, since they really only need small levels.

There should be a global NavMesh bake function that can be called from any object any time. It would bake based on your NavMeshSurfaces. Having that would allow good control over when and how to bake your NavMeshes. It should only be called when the game starts or the level is changed and sometimes it has to be called from many different objects.

I believe the manual could be improved. There should be a step by step guide on how to set up a random level with baked navmeshes. An example for that would be really helpful as well. More scripts to help get this system working would help a lot too. The dungeon level didn't work when i first tried it (it did work other time) and most scripts don't seem to be working at the moment (maybe i'm not using them right). A good summary on what scripts do would help a lot too.

Currently this system seems really difficult to use but that's most likely just because it's WIP. Information about where this system is heading and what it should be like when it is finished would help a lot too. You might also get better feedback this way.

**Comment by jakobhu** [comment]
please have a look at the examples in the github repos. https://github.com/Unity-Technologies/NavMeshComponents/tree/master/Assets/Examples
