### ISSUE TITLE
How can i get the "agentTypeID" ?

### ISSUE THREAD

**Issue by KeyleXiao** [Unity-Technologies/NavMeshComponents#50]
``` cs
     var meshAgent = unit.mTransform.gameObject.AddComponent<NavMeshAgent>();
     meshAgent.agentTypeID = ???;           <------- 
```

**Comment by KeyleXiao** [comment]
Current UNITY3D version " 2017.2.0f3 64bit "

**Comment by turadr** [comment]
Hi,
If you use the NavMeshSurface component to bake the NavMesh then the surface has an [agentTypeID ](https://github.com/Unity-Technologies/NavMeshComponents/blob/22dc5fe0b393f5a83ec4f3cc54a348eed3b14019/Assets/NavMeshComponents/Scripts/NavMeshSurface.cs#L20) property. 

Alternatively, if you want to get lower level access to the agent types in the project then you can use code similar to [this](https://github.com/Unity-Technologies/NavMeshComponents/blob/22dc5fe0b393f5a83ec4f3cc54a348eed3b14019/Assets/NavMeshComponents/Editor/NavMeshComponentsGUIUtility.cs#L38):
``` // This code obtains the IDs of agent types and also their names
            var count = NavMesh.GetSettingsCount();
            var agentTypeNames = new string[count + 2];
            for (var i = 0; i < count; i++)
            {
                var id = NavMesh.GetSettingsByIndex(i).agentTypeID;
                var name = NavMesh.GetSettingsNameFromID(id);
                agentTypeNames[i] = name;
            }
```
Did this help? 

_More at [Unity Answers](https://answers.unity.com)._

**Comment by KeyleXiao** [comment]
Awsome !
