### ISSUE TITLE
Assets/BattleFiels/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(20,42): error CS1729: The type `UnityEditor.IMGUI.Controls.BoxBoundsHandle' does not contain a constructor that takes `0' arguments

### ISSUE THREAD

**Issue by repeperilka** [Unity-Technologies/NavMeshComponents#52]
Assets/BattleFiels/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(20,42): error CS1729: The type `UnityEditor.IMGUI.Controls.BoxBoundsHandle' does not contain a constructor that takes `0' arguments

The same error with NavMeshModifierVolumeEditor.

**Comment by turadr** [comment]
@repeperilka Can you tell me please which Unity version do you use and which branch of this NavMeshComponents repository?

**Comment by turadr** [comment]
Not reproducible anymore.
