### ISSUE TITLE
Assets/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(52,22): error CS1502: The best overloaded method match for `UnityEditorInternal.EditMode.DoEditModeInspectorModeButton(UnityEditorInternal.EditMode.SceneViewEditMode, string, UnityEngine.GUIContent, UnityEngine.Bounds, UnityEditor.Editor)' has some invalid arguments

### ISSUE THREAD

**Issue by hbszxm** [Unity-Technologies/NavMeshComponents#55]
I have four issues with Unity 2017.1.2f1

Assets/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(52,22): error CS1502: The best overloaded method match for `UnityEditorInternal.EditMode.DoEditModeInspectorModeButton(UnityEditorInternal.EditMode.SceneViewEditMode, string, UnityEngine.GUIContent, UnityEngine.Bounds, UnityEditor.Editor)' has some invalid arguments

Assets/NavMeshComponents/Editor/NavMeshModifierVolumeEditor.cs(53,63): error CS1503: Argument `#4' cannot convert `method group' expression to type `UnityEngine.Bounds'

Assets/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs(169,26): error CS1502: The best overloaded method match for `UnityEditorInternal.EditMode.DoEditModeInspectorModeButton(UnityEditorInternal.EditMode.SceneViewEditMode, string, UnityEngine.GUIContent, UnityEngine.Bounds, UnityEditor.Editor)' has some invalid arguments

Assets/NavMeshComponents/Editor/NavMeshSurfaceEditor.cs(170,67): error CS1503: Argument `#4' cannot convert `method group' expression to type `UnityEngine.Bounds'

**Comment by turadr** [comment]
Thank you for reporting the issue. These errors were produced by code that fixed some warnings with Unity 2017.2 .
Please use the `2017.1` branch of this repo with your Unity 2017.1 and everything should work fine.

**Comment by hbszxm** [comment]
Thank You very much!
