### ISSUE TITLE
Async nav mesh building

### ISSUE THREAD

**Issue by bitinn** [Unity-Technologies/NavMeshComponents#59]
There must be way to a build nav mesh asynchronously without pausing the whole game, after all "UpdateNavMesh" is there, but I find no document on this, and the example provided is working with NavMeshBuilder API directly instead of NavMeshSurface? Why?

https://github.com/Unity-Technologies/NavMeshComponents/blob/master/Assets/Examples/Scripts/LocalNavMeshBuilder.cs

**Comment by turadr** [comment]
Is [UpdateNavMeshDataAsync ](https://docs.unity3d.com/ScriptReference/AI.NavMeshBuilder.UpdateNavMeshDataAsync.html) what you were looking for? It is used in a couple of places in this repo, for example [in NavMeshSurface.cs](https://github.com/Unity-Technologies/NavMeshComponents/blob/751ed671da86523906a32287cde27d54358569b7/Assets/NavMeshComponents/Scripts/NavMeshSurface.cs#L180).

**Comment by bitinn** [comment]
@turadr Thx I will look into it. I didn't realize NavMeshBuilder is a collection of static method. Maybe I can write my own component with it.

PS: Do you mind adding a simple explanation of NavMeshComponents' design goal to repo readme? Like, **is it aimed at incremental baking? Or is it an example of how to use NavMeshBuilder?**

As far as I know the API to build nav mesh at runtime is in Unity; while NavMeshComponents provide Editor GUI control and nicer API to work with. But at the same time it only seem to expose some of NavMeshBuilder's features, I find it kinda strange.
