### ISSUE TITLE
Can you make `Assets/NavMeshComponents` a separate repository & include it as a submodule ?

### ISSUE THREAD

**Issue by purple-movies** [Unity-Technologies/NavMeshComponents#60]
Hi, 
Is it possible to make the `NavMeshComponents` directory in this project a git-submodule so we don't have to clone the whole Unity project ?

It would help a lot if these packages were able to be added as a git-submodule in the Assets-directory of our projects, rather than cloning the whole project and copy/pasting the sub-directory. 

This would help generally with version-control as well as cut down on the size of our project repositories. Also would allow us to revision-lock what's cloned to our projects, and update the revision as needed.

**Comment by turadr** [comment]
Hi @purple-movies , that's a great idea. I'll check how this can be done properly or if there is some serious reason not to.

**Comment by purple-movies** [comment]
Hi @turadr,
I've done this with a couple of my packages and it's been working well so far. 

I'm using this with my `Boilerplate` package in this 3D Lemmings prototype I'm putting together:
https://github.com/purple-movies/lemmings-3d-prototype

Submodule config's here: 
https://github.com/purple-movies/lemmings-3d-prototype/blob/master/.gitmodules

So far I've been able to make changes in my Boilerplate-project as I find generic stuff I can reuse while working on the prototype and commit/push changes to both repositories as needed. 

Hope this helps :)

**Comment by turadr** [comment]
Now I can tell you that we're not going to add a submodule with the engine components scripts. That's because you'll be soon able to use this code as a package, which imports only the necessary scripts. See https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-741714518
