### ISSUE TITLE
RuntimeNavMeshBuilder: Source mesh Combined Mesh (root: scene) does not allow read access

### ISSUE THREAD

**Issue by kuyote** [Unity-Technologies/NavMeshComponents#63]
Receiving this error when trying to demo:

RuntimeNavMeshBuilder: Source mesh Combined Mesh (root: scene) does not allow read access. This will work in playmode in the editor but not in player
UnityEngine.AI.NavMeshBuilder:UpdateNavMeshDataAsync(NavMeshData, NavMeshBuildSettings, List`1, Bounds)
LocalNavMeshBuilder:UpdateNavMesh(Boolean) (at Assets/NavMeshComponents/Assets/Examples/Scripts/LocalNavMeshBuilder.cs:54)
<Start>c__Iterator0:MoveNext() (at Assets/NavMeshComponents/Assets/Examples/Scripts/LocalNavMeshBuilder.cs:26)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)

**Comment by kuyote** [comment]
this was caused by having the navmeshlink, and the navmeshsourcetag on the asset.

**Comment by baotap098** [comment]
I fixed this by uncheck Static gameobject store script
