### ISSUE TITLE
There is a small gap between Nav Mesh Surface and Agent in runtime.

### ISSUE THREAD

**Issue by game10en** [Unity-Technologies/NavMeshComponents#66]
When I use NavMeshSurface component, there is always a small gap between Nav Mesh Surface and Agent in runtime.
For instance, if the obj with Agent component is in 0,0,0, it will move to 0,0.033,0 once click play.
But if I use build-in Navigation to bake, there will be no gap...

**Comment by turadr** [comment]
The built-in NavMesh baker has the option to add more data in the form of a Height Mesh which improves the precision of placing the agent on the NavMesh. On the other hand, the NavMeshSurface does not have the option to add a height mesh, thus it is expected that the NavMesh will be a bit higher than the environment geometry and that's where the NavMeshAgent will sit.
