### ISSUE TITLE
Problem downloading UnityDownloadAssistant-5.5.0xNavMesh

### ISSUE THREAD

**Issue by PaulStapley** [Unity-Technologies/NavMeshComponents#7]
I'm having trouble downloading this special beta build.  The UnityDownloadAssistant times out when trying to download the component list.

Any help would be appreciated,
Thanks,
Paul.

<img width="599" alt="issue" src="https://cloud.githubusercontent.com/assets/2719117/20984845/caa8baf2-bc76-11e6-8d41-c415d894e38e.png">

**Comment by jakobhu** [comment]
5.5-experimental is no longer supported
