### ISSUE TITLE
Baking at runtime ignores the 'Include Layers' property.

### ISSUE THREAD

**Issue by samsamm777** [Unity-Technologies/NavMeshComponents#72]
When i bake a navmesh at runtime it appears to ignore the 'Include Layers' property in the navmeshsurface component. This creates an unusable navmesh as it goes around the agents. When baking the navmesh offline using the 'Bake' button on the surface component it works as expected.

Offline bake:
![offlinebake](https://user-images.githubusercontent.com/1075392/37255683-a2bc8498-2547-11e8-93e1-93b1514b37c3.PNG)

Runtime bake:
![runtimebake](https://user-images.githubusercontent.com/1075392/37255687-ad59d57c-2547-11e8-8bac-de199026b2a1.PNG)

```csharp
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;

public class NavigationManager : MonoBehaviour
{
    public NavMeshSurface surface;

    public void Rebake()
    {
        if (surface)
        {
            surface.BuildNavMesh();
        }
    }
}
```

**Comment by samsamm777** [comment]
Any feedback on this?

**Comment by jesse-scam** [comment]
Any luck here? I'm having the same issue

**Comment by turadr** [comment]
I could not reproduce the issue with Unity 2019.4.18f1. The NavMes is baked correctly taking into account the layers. I've tested with this code. 
```
using UnityEngine;
using UnityEngine.AI;

public class BuildNavMeshAtRuntime : MonoBehaviour
{
    NavMeshSurface m_Surface;

    void Start()
    {
        m_Surface = GetComponent<NavMeshSurface>();
    }

    void Update()
    {
        if (m_Surface && Time.frameCount % 200 == 0)
        {
            m_Surface.defaultArea = 2 + (m_Surface.defaultArea + 1) % 28;
            m_Surface.BuildNavMesh();
        }
    }
}
```

https://user-images.githubusercontent.com/9038468/106135697-8f15dd80-6168-11eb-8f78-557268a1d76b.mp4
