### ISSUE TITLE
Is it still in beta?

### ISSUE THREAD

**Issue by laurentopia** [Unity-Technologies/NavMeshComponents#73]
"Note: During the beta cycle features and API are subject to change."

**Comment by isurfraz** [comment]
?

**Comment by kisstakoala** [comment]
This is a mega important component, so I am sure they are looking at improving it but yeah, it should be outa github and into Unity by now. Is it not still?

**Comment by laurentopia** [comment]
It's weird, I thought it would be part of the package downloader, at least...

**Comment by Ziflin** [comment]
I'm curious as well as to the status of these components? I thought it would have been a package by now as well. The fact that the user manual directs users to GitHub to download such an important feature while leaving the old built-in components in-place is a little ridiculous.

**Comment by isurfraz** [comment]
an update 3 days ago but still no official word? Can a developer please take the time to outline the usability of this repo, or kill it so that if its not meant to be used, people know this?

**Comment by turadr** [comment]
Just to clarify before I close the issue, the API in this repository has not changed for a long time and it will remain like this for the foreseeable future, including at the forthcoming release of these scripts as a package.
