### ISSUE TITLE
Compiler errors on building

### ISSUE THREAD

**Issue by HAMINPANTS** [Unity-Technologies/NavMeshComponents#75]
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceAgentTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceAgentTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceLinkTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceLinkTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierVolumeTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceModifierVolumeTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceTests.cs(4,19): error CS0234: The type or namespace name `TestTools' does not exist in the namespace `UnityEngine'. Are you missing an assembly reference?
`
`Assets/NavMeshComponents-master/NavMeshComponents-master/Assets/Tests/NavMeshSurfaceTests.cs(5,7): error CS0246: The type or namespace name `NUnit' could not be found. Are you missing an assembly reference?
`
`Error building Player because scripts had compiler errors
`
`Build completed with a result of 'Failed'
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`
`UnityEditor.BuildPlayerWindow+BuildMethodException: 11 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (BuildPlayerOptions options) [0x00207] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:172 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (Boolean askForBuildLocation, BuildOptions defaultBuildOptions) [0x00050] in C:\buildslave\unity\build\Editor\Mono\BuildPlayerWindowBuildMethods.cs:83 
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
`

**Comment by UnnamedLand** [comment]
I had this issue as well, I got around it by placing the Tests folder inside the Assets/NavMeshComponents/Editor folder

**Comment by turadr** [comment]
Fixed now on branches `master` and `2018.1` .
