### ISSUE TITLE
Availability on Package Manager

### ISSUE THREAD

**Issue by hippocoder** [Unity-Technologies/NavMeshComponents#82]
Wondering if we could get these wonderful workflows in PM?

**Comment by turadr** [comment]
It is in our "to do" list but and it will be made available as soon as possible, most probably not earlier than a few more months.

**Comment by Arugin** [comment]
I am very interested in this too: it will greatly improve my workflow.

**Comment by Claytonious** [comment]
So ... 1+ years later - is this going to be released via package manager at some point?

**Comment by turadr** [comment]
Work is underway to publish this code as a package https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-741714518

**Comment by turadr** [comment]
It is now an experimental package for Unity 2019.4 or newer. Please follow this other discussion https://github.com/Unity-Technologies/NavMeshComponents/issues/172#issuecomment-808105998
