### ISSUE TITLE
`NavigationBaker.enabled' hides inherited member `UnityEngine.Behaviour.enabled'

### ISSUE THREAD

**Issue by enriquemorenotent** [Unity-Technologies/NavMeshComponents#88]
When I import the assets into Unity (2018.1.0f2), I get this warning.

 > Assets/Scripts/NavigationBaker.cs(8,17): warning CS0108: `NavigationBaker.enabled' hides inherited member `UnityEngine.Behaviour.enabled'. Use the new keyword if hiding was intended

Is this just bad variable naming?

**Comment by turadr** [comment]
Where did you get the NavigationBaker script from? It is not part of the NavMeshComponents.

**Comment by enriquemorenotent** [comment]
My bad, it was a script someone else wrote. Sorry.
