### ISSUE TITLE
Does not work to move an agent on moving navmesh

### ISSUE THREAD

**Issue by whuop** [Unity-Technologies/NavMeshComponents#9]
I have a box that has a NavMeshSurface on it, it works fine to move the box and the navmesh moves with it. But the agent can only move as long as the box is standing still. Is there some way to get around this to be able to walk on surfaces that are in movement?

**Comment by jakobhu** [comment]
no - it's not yet supported. From the FAQ:

_Q: Can I do moving NavMesh platforms?
A: No - new API is required for consistently moving platforms carrying agents._

**Comment by whuop** [comment]
All Allright, thanks! Must have missed that in the FAQ.

**Comment by FeikoJoosten** [comment]
Is there a possible update on this? Or maybe an ETA of when we can expect official support for this?
