### ISSUE TITLE
Is it possible and how to build a spherical world?

### ISSUE THREAD

**Issue by gzlock** [Unity-Technologies/NavMeshComponents#98]
I used 6 planes and many NavmeshLink components to form a cube, it worked but the process is very complicated.
![1](https://user-images.githubusercontent.com/2311740/47089363-4960cf80-d253-11e8-8582-38130e0f1bc4.gif)
 * The agent can walk on each meshes of the cube.

### And has another better way to make a cube world?

**Comment by MutimirEr** [comment]
This isnt possible, your best bet is the same way you constructed the cube with adjusting the slope of the NavMeshAgent so that you reduce the number of links.
